# gastruloid snakefile
configfile: "config.yaml"

rule all:
    input:
        expand('results/{case}/{structure}/{weights}_{k}_progenitors.txt', case=config['case'], structure=config['structure'], weights=config['weights'], k=config['k']),

def get_structure_flag(wc):
    structure = wc.structure
    if structure == 'tree':
        return "--enforce_tree"
    else:
        return ""

rule run:
    input:
        location_file="{case}_input_files.tsv",
        state_file="{case}_states.txt",
    output:
        prog_file="results/{case}/{structure}/{weights}_{k}_progenitors.txt",
    params:
        prefix="results/{case}/{structure}/{weights}_{k}",
        structure_flag=get_structure_flag,
    log:
        std="results/{case}/{structure}/{weights}_{k}.log",
        err="results/{case}/{structure}/{weights}_{k}.err.log",
    benchmark: "results/{case}/{structure}/{weights}_{k}.benchmark",
    shell:
        "python ../../src/cell_fate_mapping_run_ilp.py --prefix {params.prefix} -k {wildcards.k} "
        " --file_locations {input.location_file} --states_file {input.state_file} "
        " --normalize_method {wildcards.weights} "
        " {params.structure_flag} > {log.std} 2> {log.err} "